export const GRIZZLY_STATUS = {
  WAIT_CODE: 'STATUS_WAIT_CODE',
  WAIT_RETRY: 'STATUS_WAIT_RETRY',
  WAIT_RESEND: 'STATUS_WAIT_RESEND',
  CANCEL: 'STATUS_CANCEL',
  OK: 'STATUS_OK'
} as const;

export const GRIZZLY_ERRORS = {
  BAD_KEY: 'BAD_KEY',
  NO_NUMBERS: 'NO_NUMBERS',
  NO_ACTIVATION: 'NO_ACTIVATION',
  BAD_STATUS: 'BAD_STATUS',
  BAD_ACTION: 'BAD_ACTION'
} as const; 